"use client";

import { CacheProvider } from "@chakra-ui/next-js";
import { ChakraProvider } from "@chakra-ui/react";
import SimpleSidebar from "./components/SimpleSidebar";

// import "./globals.css";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CacheProvider>
          <ChakraProvider>
            {/* <SimpleSidebar /> */}
            {children}
          </ChakraProvider>
        </CacheProvider>
      </body>
    </html>
  );
}
